PlayDiscGolf/ViewModels/ScoreCard/ScoreCardGameOnViewModel.cs
using PlayDiscGolf.Models.Models.DataModels;
using PlayDiscGolf.ViewModels.Course;

namespace PlayDiscGolf.ViewModels.ScoreCard
{
    public class ScoreCardGameOnViewModel
    {
        public ScoreCardViewModel ScoreCard { get; set; }
        public HoleViewModel Hole { get; set; }
    }
}

PlayDiscGolf/ViewModels/ScoreCard/ScoreCardViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PlayDiscGolf.ViewModels.ScoreCard
{
    public class ScoreCardViewModel
    {        
        public Guid ScoreCardID { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        [Display(Name = "Creater")]
        public string UserName { get; set; }
        public string UserID { get; set; }
        public Guid CourseID { get; set; }
        public string CourseName { get; set; }
        public List<PlayerCardViewModel> PlayerCards { get; set; }
        public List<string> Friends { get; set; }
    }
}

PlayDiscGolf/ViewModels/Search/SearchFormHomePageViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PlayDiscGolf.ViewModels.Home
{
    public class SearchFormHomePageViewModel
    {
        public string Type { get; set; }
        public string Country { get; set; }
        public string Query { get; set; }
        public List<SelectListItem> Types = new List<SelectListItem>();
        [Display(Name = "Choose country")]
        public List<SelectListItem> Countries = new List<SelectListItem>();
        public List<SearchResultAjaxFormViewModel> SearchResultAjaxFormViewModel = new List<SearchResultAjaxFormViewModel>();
    }
}

PlayDiscGolf/Controllers/Course/CourseController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlayDiscGolf.Core.Services.CoursePage;
using PlayDiscGolf.ViewModels.Course;
using PlayDiscGolf.ViewModels.ScoreCard;

namespace PlayDiscGolf.Controllers.CoursePage
{
    [Authorize]
    public class CourseController : Controller
    {
        private readonly ICoursePageService _coursePageService;
        private readonly IMapper _mapper;

        public CourseController(ICoursePageService coursePageService, IMapper mapper)
        {
            _coursePageService = coursePageService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(string courseID)
        {
            var dto = await _coursePageService.GetCoursePageInformation(new Guid(courseID));



            var model = new CoursePageViewModel
            {
                CourseID = dto.CourseID,
                TotalDistance = dto.TotalDistance,
                AverageRound = dto.AverageRound,
                BestRound = dto.BestRound,
                FullName = dto.FullName,
                Holes = _mapper.Map<List<HoleViewModel>>(dto.Holes),
                Name = dto.Name,
                NumberOfRounds = dto.NumberOfRounds,
                ScoreCards = _mapper.Map<List<ScoreCardViewModel>>(dto.ScoreCards),
                TotalHoles = dto.TotalHoles,
                TotalParValue = dto.TotalParValue,
                Latitude = dto.Latitude,
                Longitude = dto.Longitude

            };  

            return View(model);
        }
      
    }
}

PlayDiscGolf/Controllers/ScoreCard/ScoreCardController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlayDiscGolf.Core.Services.Score;
using PlayDiscGolf.Core.Services.User;
using PlayDiscGolf.ViewModels.ScoreCard;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayDiscGolf.Controllers.ScoreCard
{
    [Authorize]
    public class ScoreCardController : Controller
    {

        private readonly IScoreCardService _scoreCardService;
        private readonly IMapper _mapper;
        private readonly IUserService _userService;

        public ScoreCardController(
            IScoreCardService scoreCardService,
            IMapper mapper,
            IUserService userService)
        {
            _scoreCardService = scoreCardService;
            _mapper = mapper;
            _userService = userService;
        }

        public async Task<IActionResult> CreateScoreCard(string courseID)
        {
            var dto = _scoreCardService.GetScoreCardCreateInformation(courseID);
            var userFriends = await _userService.GetFriendsAsync();

            var model = new ScoreCardViewModel
            {
                CourseID = dto.CourseID,
                EndDate = dto.EndDate,
                StartDate = dto.StartDate,
                UserID = dto.UserID,
                PlayerCards = _mapper.Map<List<PlayerCardViewModel>>(dto.PlayerCards),
                ScoreCardID = dto.ScoreCardID,
                UserName = dto.UserName,
                Friends = userFriends.Select(x => x.UserName).ToList(),
                CourseName = _scoreCardService.GetCourseName(dto.CourseID)                
            };

            return View(model);
        }


        public async Task<IActionResult> AddPlayer(string newName)
        {
            var model = _mapper.Map<List<PlayerCardViewModel>>(await _scoreCardService.AddPlayerToSessionAndReturnUpdatedPlayersAsync(newName));

            return PartialView("_PlayersInPlayerCard", model);
        }

        public IActionResult RemovePlayer(string removePlayer)
        {
            var model = _mapper.Map<List<PlayerCardViewModel>>(_scoreCardService.RemovePlayerFromSessionAndReturnUpdatedPlayers(removePlayer));

            return PartialView("_PlayersInPlayerCard", model);
        }

        public IActionResult StartScoreCard()
        {
            var model = _mapper.Map<ScoreCardGameOnViewModel>(_scoreCardService.StartGame());

            return View("ScoreCardLive", model);
        }


        public IActionResult UpdateScoreCard(string scoreCardID, string holeNumber, string addOrRemove, string userName)
        {
            var model = _mapper.Map<ScoreCardGameOnViewModel>(_scoreCardService.UpdateScore(scoreCardID, holeNumber, addOrRemove, userName));

            return PartialView("_ScoreCardLive", model);
        }


        public IActionResult ChangeHole(string scoreCardID, string holeNumber)
        {
            var model = _mapper.Map<ScoreCardGameOnViewModel>(_scoreCardService.UpdateScore(scoreCardID, holeNumber, null, null));

            return PartialView("_ScoreCardLive", model);
        }


        public IActionResult OpenScoreCard(string scoreCardID, int HoleNumber = 1)
        {
            var model = _mapper.Map<ScoreCardGameOnViewModel>(_scoreCardService.OpenScoreCard(scoreCardID));
            model.Hole.HoleNumber = HoleNumber;

            return View("ScoreCardLive",model);
        }                   
    }
}

PlayDiscGolf/Controllers/User/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlayDiscGolf.Core.Services.Account;
using PlayDiscGolf.Core.Services.User;
using PlayDiscGolf.ViewModels.User;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlayDiscGolf.Controllers.User
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IAccountService _accountService;
        private readonly IMapper _mapper;

        public UserController(IUserService userService, IAccountService accountService, IMapper mapper)
        {
            _userService = userService;
            _accountService = accountService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var model = new UserInformationViewModel
            {
                UserID = await _accountService.GetInloggedUserIDAsync(),
                Email = await _accountService.GetEmailAsync(),
                Username = _accountService.GetUserName(),
                Friends = _mapper.Map<List<FriendViewModel>>(await _userService.GetFriendsAsync()).Where(x => x.FriendRequestAccepted == true).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SearchUser([Bind("SearchUsername")] UserInformationViewModel formModel)
        {
            var userName = await _userService.SearchUsersAsync(formModel.SearchUsername);

            var model = new UserSearchResultViewModel
            {
                UserName = userName
            };

            return PartialView("_SearchUserNameResult", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeEmail(UserChangeEmailViewModel model)
        {
            if (ModelState.IsValid)
            {
                var isEmailTaken = await _accountService.IsEmailTakenAsync(model.Email);

                if (!isEmailTaken)
                {
                    await _accountService.ChangeEmailAsync(model.Email);

                    return Json(new { success = true, responseText = "Your message successfuly sent!"});
                }

                if (isEmailTaken) ModelState.AddModelError("Email", "Email is Taken");
            }

            return PartialView("_ChangeEmail", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(UserChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _accountService.ChangePasswordAsync(model.Password);

                return Json(new { success = true, responseText = "Your message successfuly sent!"});
            }

            return PartialView("_ChangePassword", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeUsername(UserChangeUsernameViewModel model)
        {
            if (ModelState.IsValid)
            {
                var isUserNameTaken = await _accountService.IsUserNameTakenAsync(model.Username);

                if (!isUserNameTaken)
                {
                    await _accountService.ChangeUserNameAsync(model.Username);

                    return Json(new { success = true, responseText = "Your message successfuly sent!" });
                }

                if (isUserNameTaken) ModelState.AddModelError("Username", "Username is Taken");
            }

            return PartialView("_ChangeUsername", model);
        }

        public async Task<IActionResult> AddFriend(string username)
        {
            await _userService.SendFriendRequestAsync(username);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveFriend(string friendID)
        {
            await _userService.RemoveFriendAsync(friendID);

            return RedirectToAction("Index");
        }
    }
}

PlayDiscGolf/Views/Shared/_ChangeEmail.cshtml
@model PlayDiscGolf.ViewModels.User.UserChangeEmailViewModel


<div>
    <form id="ChangeEmail" asp-action="ChangeEmail" onsubmit="return jQueryAjaxPost(this);">
        <div class="form-group">
            <label for="exampleInputEmail1">Change Email address</label>

            <input type="email" asp-for="@Model.Email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email..">
            <span class="text-danger" asp-validation-for="@Model.Email"></span>
            <small id="emailHelp" class="form-text text-muted mb-1">We'll never share your email with anyone else.</small>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

PlayDiscGolf/Views/Shared/_ChangePassword.cshtml
@model PlayDiscGolf.ViewModels.User.UserChangePasswordViewModel



<div>
    <form id="ChangePassword" asp-action="ChangePassword" onsubmit="return jQueryAjaxPost(this);">
        <div class="form-group">
            <label for="exampleInputPassword1">Change password</label>
            <input type="password" asp-for="@Model.Password" class="form-control" id="exampleInputPassword1" aria-describedby="emailHelp" placeholder="Enter new password..">
            <span class="text-danger" asp-validation-for="@Model.Password"></span>
            <small id="emailHelp" class="form-text text-muted">We'll never share your password with anyone else.</small>
            <label for="exampleInputPassword2">Confirm new password</label>
            <input type="password" asp-for="@Model.ConfirmPassword" class="form-control" id="exampleInputPassword2" aria-describedby="emailHelp" placeholder="Enter password again..">
            <span class="text-danger" asp-validation-for="@Model.ConfirmPassword"></span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

PlayDiscGolf/Views/Shared/_ChangeUserName.cshtml
@model PlayDiscGolf.ViewModels.User.UserChangeUsernameViewModel


<div>
        <form id="ChangeUsername" asp-action="ChangeUsername" onsubmit="return jQueryAjaxPost(this);">
            <div class="form-group">
                <label for="exampleInputEmail1">Change username</label>
                <input asp-for="@Model.Username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter username..">
                <span class="text-danger" asp-validation-for="@Model.Username"></span>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
</div>

PlayDiscGolf/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using PlayDiscGolf.Core.Services.User

@inject SignInManager<IdentityUser> signInManager;
@inject RoleManager<IdentityRole> roleManager;
@inject IUserService _userService;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlayDiscGolf</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,500&amp;subset=latin-ext" rel="stylesheet" asp-append-version="true" >
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet" asp-append-version="true" >
    

</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-dark badge-secondary box-shadow mb-5">
            <div class="container">
                <a class="navbar-brand hover-shadow text-success h5 pl-2 pr-2" asp-area="" asp-controller="Home" asp-action="Index">PlayDiscGolf</a>
                <button id="ToggleNavbar" class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">

                    <span class="text-success" >
                        <i class="fas fa-bars fa-2x"></i>
                    </span>
                </button>
                <div class="navbar-collapse hover-shadow collapse d-sm-inline-flex flex-sm-row-reverse">

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link hover-shadow text-success h5" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link hover-shadow text-success h5" asp-area="" asp-controller="Admin" asp-action="Index">Edit Courses</a>
                            </li>
                        }

                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link hover-shadow text-success h5" asp-area="" asp-controller="User" asp-action="Index">My page</a>
                            </li>


                            var model = await _userService.GetFriendRequestsAsync();

                            var notificationCount = "0";

                            if (model.Count() > 0)
                            {
                                notificationCount = model.Count().ToString();

                                <li class="nav-item">
                                    <a class="nav-link hover-shadow text-success h5" asp-area="" asp-controller="Notification" asp-action="Index">Notification (@notificationCount)</a>
                                </li>
                            }

                            <li class="nav-item ml-lg-2">
                                <a class="nav-link hover-shadow text-success h5" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item ml-lg-2">
                                <a class="nav-link hover-shadow text-success" asp-area="" asp-controller="User" asp-action="Index">Username: @User.Identity.Name</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ml-lg-2">
                                <a class="nav-link hover-shadow text-success h5" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item ml-lg-2">
                                <a class="nav-link hover-shadow text-success h5" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container text-success text-center">
            &copy; 2021 - PlayDiscGolf
        </div>
    </footer>
    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false).ConfigureAwait(false)

</body>
</html>

PlayDiscGolf/Views/Shared/_PlayersInPlayerCard.cshtml
@model List<PlayDiscGolf.ViewModels.ScoreCard.PlayerCardViewModel>

<div class="card-body" style="overflow-y: auto">
    <div class="d-flex mb-3">
        <div id="" class="pt-2 h5">@Model[0].UserName</div>
    </div>
</div>

@if (Model.Count > 1)
{
    for (int i = 1; i < Model.Count; i++)
    {
        <div class="card-body" style="overflow-y: auto">
            <div class="d-flex ">
                <div id="" class="pt-2 h5">@Model[i].UserName</div>
                <div class="ml-auto d-flex mt-0">
                    <div class="pb-0">
                        <a data-ajax="true" data-ajax-method="Get" data-ajax-mode="replace" data-ajax-update="#playersInScoreCard" asp-action="RemovePlayer" asp-controller="ScoreCard" asp-route-removePlayer="@Model[i].UserName" id="@Model[i].UserName" class="btn text-success">
                            <span style="color:tomato"><i class="far fa-minus-square fa-2x"></i></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    }
}

PlayDiscGolf/Views/Shared/_ScoreCardLive.cshtml
@using PlayDiscGolf.ViewModels.ScoreCard

@model ScoreCardGameOnViewModel

@{
    Layout = null;
    var currentPage = Model.Hole.HoleNumber;
    var numberofHoleslooped = 0;
    var leftArrowHoleNumber = Model.Hole.HoleNumber - 1;
    var rightArrowHoleNumber = 0;
    var players = Model.ScoreCard.PlayerCards;


    if (Model.Hole.HoleNumber != 1)
    {
        rightArrowHoleNumber = Model.Hole.HoleNumber + 4;
    }
    else
    {
        rightArrowHoleNumber = Model.Hole.HoleNumber + 5;
    }
}
<div class="justify-content-between border-bottom border-dark m-0 text-center d-flex" style="background-color:#cccccc">
    <p class="h5 pl-3 pt-2 pt-b-3">Hole: @Model.Hole.HoleNumber </p>
    <p class="h5 pl-0 pt-2 pt-b-3">Par: @Model.Hole.ParValue</p>
    <p class="h5 pr-3 pt-2 pt-b-3">Distance: @Model.Hole.Distance m</p>
</div>

<div class="bg-transparent">
    <div class="card-body bg-warning" style="overflow-y: auto">

        @foreach (var player in players)
        {
            var holeCard = (player.HoleCards as IEnumerable<HoleCardViewModel>
            ).FirstOrDefault(h => h.HoleNumber == Model.Hole.HoleNumber);

            <div class="d-flex mb-3">
                @if (@player.TotalScore <= 0)
                {
                    <div class="pt-2 h5">@player.UserName (@player.TotalScore)</div>
                }
                else
                {
                    <div class="pt-2 h5">@player.UserName (+@player.TotalScore)</div>
                }
                <div class="ml-auto d-flex mt-0">
                    <div class="pb-0">
                        <a type="button" id="@player.UserName" class="btn text-success" asp-action="UpdateScoreCard" asp-controller="ScoreCard"
                           asp-route-scoreCardID="@Model.ScoreCard.ScoreCardID.ToString()" asp-route-holeNumber="@Model.Hole.HoleNumber.ToString()" asp-route-addOrRemove="Minus"
                           asp-route-userName="@player.UserName" asp-route-courseID="@Model.ScoreCard.CourseID.ToString()" data-ajax="true" data-ajax-method="Get" data-ajax-mode="replace" data-ajax-update="#scoreCardLive">
                            <span style="color:tomato"><i class="far fa-minus-square fa-2x"></i></span>
                        </a>
                    </div>
                    @if (holeCard == null || holeCard.Score == 0)
                    {
                        <div class="pt-2 h4">0</div>
                    }
                    else
                    {
                        <div class="pt-2 h4">@holeCard.Score</div>
                    }
                    <div class="pb-0">
                        <a type="button" id="@player.PlayerCardID" class="btn text-success" asp-action="UpdateScoreCard" asp-controller="ScoreCard"
                           asp-route-scoreCardID="@Model.ScoreCard.ScoreCardID.ToString()" asp-route-holeNumber="@Model.Hole.HoleNumber.ToString()" asp-route-addOrRemove="Plus"
                           asp-route-userName="@player.UserName" asp-route-courseID="@Model.ScoreCard.CourseID.ToString()" data-ajax="true" data-ajax-method="Get" data-ajax-mode="replace" data-ajax-update="#scoreCardLive">
                            <i class="far fa-plus-square fa-2x"></i>
                        </a>
                    </div>
                </div>
            </div>
        }

    </div>
    <div class="bg-transparent">
        <nav class="bg-transparent" aria-label="...">

            <ul class="pagination pagination-lg  justify-content-center">
                @if (currentPage != 1)
                {
                    <li class="page-item">
                        <a class="page-link" aria-label="Previous" asp-action="ChangeHole" asp-controller="ScoreCard"
                           asp-route-scoreCardID="@Model.ScoreCard.ScoreCardID.ToString()" asp-route-holeNumber="@leftArrowHoleNumber.ToString()" asp-route-courseID="@Model.ScoreCard.CourseID.ToString()"
                           data-ajax="true" data-ajax-method="Get" data-ajax-mode="replace" data-ajax-update="#scoreCardLive">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    numberofHoleslooped++;
                }

                @{
                    var startpage = currentPage;

                    if(Model.ScoreCard.PlayerCards[0].HoleCards != null)
                    {
                        if (Model.ScoreCard.PlayerCards[0].HoleCards.Count > 5)
                        {
                            if (Model.Hole.HoleNumber + 1 == Model.ScoreCard.PlayerCards[0].HoleCards.Count)
                            {
                                startpage = startpage - 1;
                            }

                            if (Model.Hole.HoleNumber == Model.ScoreCard.PlayerCards[0].HoleCards.Count)
                            {
                                startpage = startpage - 2;
                            }
                        }
                    }
                }
                
                @for (int i = startpage; i < Model.ScoreCard.PlayerCards[0].HoleCards.Count + 1; i++)
                {
                    numberofHoleslooped++;

                    @if (Model.Hole.HoleNumber == i)
                    {
                        <li class="page-item active">
                            <a class="page-link" asp-action="ChangeHole" asp-controller="ScoreCard"
                               asp-route-scoreCardID="@Model.ScoreCard.ScoreCardID.ToString()" asp-route-holeNumber="@Model.Hole.HoleNumber.ToString()" asp-route-courseID="@Model.ScoreCard.CourseID.ToString()"
                               data-ajax="true" data-ajax-method="Get" data-ajax-mode="replace" data-ajax-update="#scoreCardLive">@i <span class="sr-only">(current)</span></a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" asp-action="ChangeHole" asp-controller="ScoreCard"
                               asp-route-scoreCardID="@Model.ScoreCard.ScoreCardID.ToString()" asp-route-holeNumber="@i.ToString()" asp-route-courseID="@Model.ScoreCard.CourseID.ToString()"
                               data-ajax="true" data-ajax-method="Get" data-ajax-mode="replace" data-ajax-update="#scoreCardLive">@i</a>
                        </li>
                    }
                    if (numberofHoleslooped == 4)
                    {
                        if (Model.Hole.HoleNumber + 3 == Model.ScoreCard.PlayerCards[0].HoleCards.Count)
                        {

                        }
                        else
                        {
                            break;
                        }

                    }
                }
                @if (Model.Hole.HoleNumber + 3 != Model.ScoreCard.PlayerCards[0].HoleCards.Count)
                {
                    @if (((Model.Hole.HoleNumber + 2) < Model.ScoreCard.PlayerCards[0].HoleCards.Count))
                    {
                        <li class="page-item">
                            <a class="page-link" aria-label="Next" asp-action="ChangeHole" asp-controller="ScoreCard"
                               asp-route-scoreCardID="@Model.ScoreCard.ScoreCardID.ToString()" asp-route-holeNumber="@rightArrowHoleNumber.ToString()" asp-route-courseID="@Model.ScoreCard.CourseID.ToString()"
                               data-ajax="true" data-ajax-method="Get" data-ajax-mode="replace" data-ajax-update="#scoreCardLive">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    }
                }

            </ul>
        </nav>
    </div>
</div>

PlayDiscGolf/Views/Shared/_SearchFormHomePage.cshtml
@model PlayDiscGolf.ViewModels.Home.SearchFormHomePageViewModel

@{
    Layout = null;
}
<form id="SearchFormAjax" asp-action="SearchFormAjax" onsubmit="return jQueryAjaxPost(this);">
    <div class="form-group row">
        <input hidden asp-for="@Model.Countries" />
        <input hidden asp-for="@Model.Types" />
        <div class="col-sm-2 ml-xl-2 pb-4">
            <span class="text-danger" asp-validation-for="@Model.Country"></span>
            <select class=" form-control" asp-for="@Model.Country" asp-items="@Model.Countries">
            </select>
        </div>
        <div class="col-sm-2 ml-xl-2 pb-4">
            <span class="text-danger" asp-validation-for="@Model.Type"></span>
            <select class="form-control" asp-for="@Model.Type" asp-items="@Model.Types">
            </select>
        </div>
        <div class="col-sm-4 ml-xl-2 pb-4">
            <span class="text-danger" asp-validation-for="@Model.Query"></span>
            <input placeholder="Search here.." class="form-control" id="searchCourse" asp-for="@Model.Query">
        </div>
        <div class="col-sm-2 ml-xl-2 pb-4">
            <input type="submit" class="btn btn-primary mb-2 form-control" value="Search" />
        </div>
    </div>
</form>
<div id="searchFormResultHomePage" class="text-center">
    @await Html.PartialAsync("_SearchFormResultHomePage", Model.SearchResultAjaxFormViewModel)
</div>

<script src="~/js/site.js" asp-append-version="true"></script>

PlayDiscGolf/Views/Shared/_SearchFormResultHomePage.cshtml
@using PlayDiscGolf.ViewModels.Home

@model List<SearchResultAjaxFormViewModel>
@{
    Layout = null;
}


    @if (Model.Count > 0)
    {
        <ul class="list-unstyled">
            @foreach (var item in Model)
            {
                <li class="mb-3">
                    <a type="button" asp-action="Index" asp-controller="Course" asp-route-courseID="@item.CourseID.ToString()" class="btn btn-primary" id="@item.CourseID.ToString()">@item.FullName</a>
                </li>
            }
        </ul>
    }

PlayDiscGolf/Views/Shared/_SearchUserNameResult.cshtml
@model PlayDiscGolf.ViewModels.User.UserSearchResultViewModel

@{
    Layout = null;
}

@if (Model.UserName != null)
{
<div class="d-flex">
    <p class="pl-4 mt-2">@Model.UserName</p>
    <a class="btn btn-success mb-5" style="margin-left:10%" asp-route-username="@Model.UserName" asp-action="AddFriend" asp-controller="User">Send friend request</a>
</div>
}