PlayDiscGolf/Controllers/Notification/NotificationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PlayDiscGolf.Core.Services.User;
using PlayDiscGolf.ViewModels.User;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PlayDiscGolf.Controllers.User
{
    [Authorize]
    public class NotificationController : Controller
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;

        public NotificationController(IUserService userService, IMapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var model = _mapper.Map<List<FriendViewModel>>(await _userService.GetFriendRequestsAsync());

            if(model.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        public IActionResult DeclineFriendRequest(string friendID)
        {
            _userService.DeclineFriendRequest(friendID);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AcceptFriendRequest(string friendID)
        {
            await _userService.AcceptFriendRequestAsync(friendID);

            return RedirectToAction("Index");
        }
    }
}

PlayDiscGolf/Views/Notification/Index.cshtml
@model List<PlayDiscGolf.ViewModels.User.FriendViewModel>

@if (Model.Count > 0)
{
    <div class="row pt-5 m-auto row justify-content-md-center bg-transparent">
        <div class="col-md-6 col-lg-6 pb-3">
                <table class="container table table-warning">
                    <thead>
                        <tr>
                            <th scope="col">Friend Request</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var request in Model)
                        {
                            <tr>
                                <td>@request.UserName</td>
                                <td><a class="text-success" asp-route-friendID="@request.FriendID" asp-action="AcceptFriendRequest" asp-controller="Notification">Accept</a></td>
                                <td><a class="text-danger" asp-route-friendID="@request.FriendID" asp-action="DeclineFriendRequest" asp-controller="Notification">Decline</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            
        </div>
    </div>
}