PlayDiscGolf/ViewModels/AdminCourse/AdminSearchViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PlayDiscGolf.Models.Models.DataModels;
using PlayDiscGolf.Models.ViewModels.PostModels;
using PlayDiscGolf.ViewModels.Home;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace PlayDiscGolf.Models.ViewModels
{
    public class AdminSearchViewModel
    {
        public string Type { get; set; }
        public string Country { get; set; }
        public string Query { get; set; }
        public List<SelectListItem> Types = new List<SelectListItem>();
        public List<SelectListItem> Countries = new List<SelectListItem>();
        public CourseFormViewModel Course { get; set; }
        public List<SearchResultAjaxFormViewModel> SearchResultAjaxFormViewModel = new List<SearchResultAjaxFormViewModel>();

    }
}

PlayDiscGolf/ViewModels/AdminCourse/CreateHolesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using static PlayDiscGolf.Models.ViewModels.CourseFormViewModel;

namespace PlayDiscGolf.Models.ViewModels
{
    public class CreateHolesViewModel
    {
        public int NumberOfHoles { get; set; }
        public Guid CourseID { get; set; }
        public List<CourseHolesViewModel> Holes = new List<CourseHolesViewModel>();       
    }
}

PlayDiscGolf/Controllers/AdminCourseController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using PlayDiscGolf.Models.ViewModels;
using PlayDiscGolf.Services.Admin;
using Newtonsoft.Json;
using PlayDiscGolf.Models.DataModels;

namespace PlayDiscGolf.Controllers
{
    public class AdminCourseController : Controller
    {
        private readonly IAdminService _adminService;
        private readonly IMapper _mapper;

        public AdminCourseController(IAdminService adminService, IMapper mapper)
        {
            _adminService = adminService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var model = new AdminSearchViewModel();

            return View(model);
        }


        public async Task<IActionResult> Search(string query, string searchType)
        {
            var model = new List<SearchCourseItemViewModel>();

            if (!string.IsNullOrWhiteSpace(query) && searchType == "1")
            {
                model = _mapper.Map<List<SearchCourseItemViewModel>>(await _adminService.GetCoursesByLocationQuery(query));
            }
            else if(!string.IsNullOrWhiteSpace(query) && searchType == "2")
            {
                model = _mapper.Map<List<SearchCourseItemViewModel>>(await _adminService.GetCoursesByCourseNameQuery(query));
            }
               

            return PartialView("_CourseSearchResult", model);
        }

        public async Task<PartialViewResult> SelectedLocation(Guid id)
        {
            var model = _mapper.Map<CourseFormViewModel>(await _adminService.GetCourseByID(id));
            model.Holes = _mapper.Map<List<CourseFormViewModel.CourseHolesViewModel>>(await _adminService.GetCoursesHoles(model.CourseID));

            return PartialView("_CourseForm", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> EditCourse(CourseFormViewModel model)
        {
            if(!ModelState.IsValid)
            {
                var parentModel = new AdminSearchViewModel();
                parentModel.Course = model;
                return View("Index", parentModel);
            }

            await _adminService.SaveUpdatedCourse(_mapper.Map<Course>(model));

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetHoles(string holes, string courseID)
        {
            var model = new CreateHolesViewModel
            {
                NumberOfHoles = Convert.ToInt32(holes),
                CourseID = Guid.Parse(courseID),
                Holes = _mapper.Map<List<CourseFormViewModel.CourseHolesViewModel>>(await _adminService.GetCoursesHoles(Guid.Parse(courseID)))
            };

            if(model.Holes.Count < model.NumberOfHoles)
            {
                for (int i = model.Holes.Count; i < model.NumberOfHoles; i++)
                {
                    model.Holes.Add(new CourseFormViewModel.CourseHolesViewModel
                    {
                        CourseID = model.CourseID,
                        HoleNumber = i + 1,
                        HoleID = Guid.NewGuid(),
                        ParValue = 1,
                        Distance = 1
                    });
                }
            }
            else if(model.Holes.Count > model.NumberOfHoles)
            {
                var newHolesList = model.Holes;
                for (int i = model.NumberOfHoles; i < model.Holes.Count; i++)
                {
                    newHolesList.RemoveAt(i);
                }
                model.Holes = newHolesList;
            }
            

            return PartialView("_CreateHoles",model);
        }
    }
}

PlayDiscGolf/Views/AdminCourse/_CourseFormPartial.cshtml
@model PlayDiscGolf.Models.ViewModels.CourseFormViewModel

@{
    Layout = null;
    var holeCount = 0;

    if (Model.Holes == null || Model.Holes.Count < 1)
    {
        holeCount = 0;
    }
    else if (Model.Holes.Count > 0)
    {
        holeCount = Model.HolesTotal;
    }
}

@if (!string.IsNullOrEmpty(Model.Name))
{
    <div class="container mb-4">
        <form method="post" asp-action="EditCourse" asp-controller="AdminCourse">
            @Html.AntiForgeryToken()
            <input hidden asp-for="@Model.CreateHolesViewModel" value="@Model.CreateHolesViewModel">
            @if (Model.CreateHolesViewModel != null)
            {
                <input hidden asp-for="@Model.CreateHolesViewModel.CourseID" value="@Model.CreateHolesViewModel.CourseID">
                <input hidden asp-for="@Model.CreateHolesViewModel.Holes" value="@Model.CreateHolesViewModel.Holes">
            }
            <input hidden asp-for="@Model.CourseID" value="@Model.CourseID">
            <input hidden asp-for="@Model.ApiID" value="@Model.ApiID">
            <input hidden asp-for="@Model.ApiParentID" value="@Model.ApiParentID">
            <input hidden asp-for="@Model.FullName" value="@Model.FullName">
            <input hidden asp-for="@Model.CountryCode" value="@Model.CountryCode">
            <input hidden asp-for="@Model.Longitude" value="@Model.Longitude">
            <input hidden asp-for="@Model.Latitude" value="@Model.Latitude">
            <input id="courseID" type="text" hidden value="@Model.CourseID.ToString()">

            <div class="form-group">
                <span class="text-warning" asp-validation-for="@Model.Name"></span>
                <label asp-for="@Model.Area"></label>
                <input asp-for="@Model.Area" type="text" class="form-control" id="areaInput" aria-describedby="areaInput" placeholder="">
            </div>
            <div class="form-group">
                <span class="text-warning" asp-validation-for="@Model.Name"></span>
                <label asp-for="@Model.Name"></label>
                <input asp-for="@Model.Name" type="text" class="form-control" id="nameInput" aria-describedby="nameInput" placeholder="">
            </div>
            <div class="form-check">
                <input asp-for="@Model.Main" type="checkbox" class="form-check-input" id="exampleCheck1">
                <label asp-for="@Model.Main" class="form-check-label"></label>
            </div>

            <div class="form-group mt-4">
                <span class="text-warning" asp-validation-for="@Model.HolesTotal"></span>
                <label asp-for="@Model.HolesTotal"></label>
                <input asp-for="@Model.HolesTotal" type="number" class="form-control" id="editHoles" aria-describedby="holesInput" placeholder="">
            </div>
            @if (holeCount >= 0)
            {
                <p>
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#partialHoles" aria-expanded="false" aria-controls="partialHoles">
                        Show Holes
                    </button>
                </p>
                <div class="collapse" id="partialHoles">
                    @await Html.PartialAsync("_createHoles", Model.CreateHolesViewModel)
                </div>
            }
            
            <div class="form-group">
                <span class="text-warning" asp-validation-for="@Model.TotalParValue"></span>
                <label asp-for="@Model.TotalParValue"></label>
                <input asp-for="@Model.TotalParValue" type="number" class="form-control" id="parvalueInput" aria-describedby="parvalueInput" placeholder="">
            </div>
            <div class="form-group">
                <span class="text-warning" asp-validation-for="@Model.TotalDistance"></span>
                <label asp-for="@Model.TotalDistance"></label>
                <input asp-for="@Model.TotalDistance" type="number" class="form-control" id="distanceInput" aria-describedby="distanceInput" placeholder="">
            </div>
            <input type="submit" class="btn btn-primary" value="Submit" />
        </form>


    </div>
                    
 }
<script src="~/js/site.js" asp-append-version="true"></script>